import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
const inter = Poppins({ subsets: ["latin"] ,weight:['400']});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <div className="min-h-[600px]">
            {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
